name: Deploy on Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          # Add your deployment steps here
          echo "Deploying release ${{ github.ref }}"
